steps:
# Build the container image with build-time environment variables
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '--build-arg', 'VITE_GEMINI_API_KEY=$$GEMINI_API_KEY',
         '-t', 'gcr.io/myresume-457817/ai-video-generator', '.']
  secretEnv: ['GEMINI_API_KEY']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/myresume-457817/ai-video-generator']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ai-video-generator'
  - '--image'
  - 'gcr.io/myresume-457817/ai-video-generator'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--port'
  - '8080'
  - '--set-env-vars'
  - 'NODE_ENV=production,voiceName=Fenrir,voiceModel=gemini-2.5-flash-preview-tts,videoModel=veo-2.0-generate-001'
  - '--update-secrets'
  - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest'

images:
- 'gcr.io/myresume-457817/ai-video-generator'

availableSecrets:
  secretManager:
  - versionName: projects/myresume-457817/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY

